---
- name: Install AWS CLI 2
  tasks:
    - name: Download and unzip archive
      ansible.builtin.unarchive:
        src: https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip
        dest: ~/Downloads
        remote_src: true

    - name: Execute shell
      ansible.builtin.shell: sudo ~/Downloads/aws/install
      args:
        executable: "{{ shell }}"

    - name: Recursively remove directory
      ansible.builtin.file:
        path: ~/Downloads/aws
        state: absent
